/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Entity.Clients;
import Entity.Phones;
import faciliti.Tolls;
import static forms.frmAdd.TxtNumberOperation2;
import static forms.frmAdd.s;
import static forms.frmPhoneUpdate.TxtNumberOperation3;

//import static forms.frmsearch.s;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 *
 * @author YOUCEF
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form fromMain
     */
    private static frmMain obj = null;

    public frmMain() {
        initComponents();

    }

    public static frmMain GetObj() {
        if (obj == null) {
            obj = new frmMain();
        }
        return obj;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        BtnDelete1 = new javax.swing.JButton();
        BtnDelete2 = new javax.swing.JButton();
        BtnDelete3 = new javax.swing.JButton();
        BtnDelete5 = new javax.swing.JButton();
        BtnDelete6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(125, 41));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Table1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Table1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "عدد الاقصاط المابقية", "عدد الاقصاط", "المبلغ المتبقي", "المبلغ المدفوع", "ثمن السلعة", "تاريخ البيع", "السلعة المباعة ", "رقم البطاقة", "العنوان", "الاسم الرباعي", "رقم"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        Table1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);
        if (Table1.getColumnModel().getColumnCount() > 0) {
            Table1.getColumnModel().getColumn(10).setMaxWidth(60);
        }

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/Exit.png"))); // NOI18N
        jButton1.setText("خروج");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/add.png"))); // NOI18N
        btnAdd.setText("إضافة");
        btnAdd.setMaximumSize(new java.awt.Dimension(125, 41));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/refresh.png"))); // NOI18N
        jButton2.setText("تحديث");
        jButton2.setMaximumSize(new java.awt.Dimension(125, 41));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BtnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        BtnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/modify.png"))); // NOI18N
        BtnUpdate.setText("تعديل");
        BtnUpdate.setMaximumSize(new java.awt.Dimension(125, 41));
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setBackground(new java.awt.Color(255, 255, 255));
        BtnDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/delete2.png"))); // NOI18N
        BtnDelete.setText("حذف");
        BtnDelete.setMaximumSize(new java.awt.Dimension(125, 41));
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        Table2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "أرقام الهاتف"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Table2);

        BtnDelete1.setBackground(new java.awt.Color(255, 255, 255));
        BtnDelete1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/password.png"))); // NOI18N
        BtnDelete1.setText("كلمة السر");
        BtnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelete1ActionPerformed(evt);
            }
        });

        BtnDelete2.setBackground(new java.awt.Color(255, 255, 255));
        BtnDelete2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnDelete2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/search.png"))); // NOI18N
        BtnDelete2.setText("بحث");
        BtnDelete2.setMaximumSize(new java.awt.Dimension(125, 41));
        BtnDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelete2ActionPerformed(evt);
            }
        });

        BtnDelete3.setBackground(new java.awt.Color(255, 255, 255));
        BtnDelete3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnDelete3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/pdf.png"))); // NOI18N
        BtnDelete3.setText("تقارير");
        BtnDelete3.setMaximumSize(new java.awt.Dimension(125, 41));
        BtnDelete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelete3ActionPerformed(evt);
            }
        });

        BtnDelete5.setBackground(new java.awt.Color(255, 255, 255));
        BtnDelete5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnDelete5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/print.png"))); // NOI18N
        BtnDelete5.setText("طباعة");
        BtnDelete5.setMaximumSize(new java.awt.Dimension(125, 41));
        BtnDelete5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelete5ActionPerformed(evt);
            }
        });

        BtnDelete6.setBackground(new java.awt.Color(255, 255, 255));
        BtnDelete6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnDelete6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/java.png"))); // NOI18N
        BtnDelete6.setText("المبرمج");
        BtnDelete6.setMaximumSize(new java.awt.Dimension(125, 41));
        BtnDelete6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelete6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnDelete6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 26, Short.MAX_VALUE)
                        .addComponent(BtnDelete1)
                        .addGap(27, 27, 27)
                        .addComponent(BtnDelete3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(BtnDelete5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(BtnDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public static Clients s = new Clients();
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Tolls.drawRect(this, Color.BLACK, 15);
        //this.getContentPane().setBackground(new java.awt.Color(255, 255, 255));

       /* BtnDelete.setBorderPainted(false);
        BtnDelete.setFocusPainted(false);
        BtnDelete1.setBorderPainted(false);
        BtnDelete1.setFocusPainted(false);
        BtnDelete2.setBorderPainted(false);
        BtnDelete2.setFocusPainted(false);
        BtnDelete3.setBorderPainted(false);
        BtnDelete3.setFocusPainted(false);
        BtnDelete5.setBorderPainted(false);
        BtnDelete5.setFocusPainted(false);
        BtnDelete6.setBorderPainted(false);
        BtnDelete6.setFocusPainted(false);
        BtnUpdate.setBorderPainted(false);
        BtnUpdate.setFocusPainted(false);
        btnAdd.setBorderPainted(false);
        btnAdd.setFocusPainted(false);
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setFocusPainted(false);
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);*/
        Tolls.MakeTrans(this);
        Tolls.TableColor(Table1);
        Tolls.TableColor(Table2);
        Tolls.TableArabic(Table1);
        Tolls.TableArabic(Table2);
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd  hh-mm-ss");
        Date d = new Date();
        String DateNow = f.format(d);
        //jLabel1.setText(DateNow);
        Table1.getTableHeader().setReorderingAllowed(false);

        BtnDelete.setEnabled(false);
        BtnUpdate.setEnabled(false);
        s.getAllRows(Table1);

    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean test = Tolls.ConfigMsg("هل تريد الخروج ؟");
        if (test) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Tolls.OpenForm(frmAdd.getObj(), "اضافة");
    }//GEN-LAST:event_btnAddActionPerformed
    Clients c = new Clients();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Table1.getTableHeader().setReorderingAllowed(false);
        ph.getAllRows(frmPhoneUpdate.Table3);
        BtnDelete.setEnabled(false);
        BtnUpdate.setEnabled(false);
        s.getAllRows(Table1);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        Tolls.OpenForm(frmUpdate.getObj(), "تعديل");
        int row = -1;
        row = Table1.getSelectedRow();
        if (row != -1) {
            frmUpdate.TxtNumberOperation2.setText(Table1.getValueAt(row, 10).toString());
            frmUpdate.TxtName2.setText(Table1.getValueAt(row, 9).toString());
            frmUpdate.TxtAdress2.setText(Table1.getValueAt(row, 8).toString());
            frmUpdate.TxtIdCard2.setText(Table1.getValueAt(row, 7).toString());
            frmUpdate.TxtProdSell2.setText(Table1.getValueAt(row, 6).toString());
            SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
            try {
                frmUpdate.DCDate2.setDate(d.parse((String) Table1.getValueAt(row, 5)));
            } catch (ParseException ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            frmUpdate.TxtPriceProdSell2.setText(Table1.getValueAt(row, 4).toString());
            frmUpdate.TxtPricePay2.setText(Table1.getValueAt(row, 3).toString());
            frmUpdate.TxtPriceStill2.setText(Table1.getValueAt(row, 2).toString());
            frmUpdate.TxtNumberParts2.setText(Table1.getValueAt(row, 1).toString());
            frmUpdate.TxtNumberPartsStill2.setText(Table1.getValueAt(row, 0).toString());
        }
        BtnDelete.setEnabled(false);
        BtnUpdate.setEnabled(false);


    }//GEN-LAST:event_BtnUpdateActionPerformed
    public static frmUpdate u = new frmUpdate();
    Phones ph = new Phones();
    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked

        int row = Table1.getSelectedRow();
        System.out.println(row);
        frmUpdate.TxtNumberOperation2.setText(Table1.getValueAt(row, 10).toString());
        frmUpdate.TxtName2.setText(Table1.getValueAt(row, 9).toString());
        frmUpdate.TxtAdress2.setText(Table1.getValueAt(row, 8).toString());
        frmUpdate.TxtIdCard2.setText(Table1.getValueAt(row, 7).toString());
        frmUpdate.TxtProdSell2.setText(Table1.getValueAt(row, 6).toString());
        SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        try {
            frmUpdate.DCDate2.setDate(d.parse((String) Table1.getValueAt(row, 5)));
        } catch (ParseException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmUpdate.TxtPriceProdSell2.setText(Table1.getValueAt(row, 4).toString());
        frmUpdate.TxtPricePay2.setText(Table1.getValueAt(row, 3).toString());
        frmUpdate.TxtPriceStill2.setText(Table1.getValueAt(row, 2).toString());
        frmUpdate.TxtNumberParts2.setText(Table1.getValueAt(row, 1).toString());
        frmUpdate.TxtNumberPartsStill2.setText(Table1.getValueAt(row, 0).toString());

        ph.setNumberOperation(Integer.parseInt(Table1.getValueAt(row, 10).toString()));
        ph.getAllRows(Table2);

        BtnDelete.setEnabled(true);
        BtnUpdate.setEnabled(true);


    }//GEN-LAST:event_Table1MouseClicked

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed

        int n = Table1.getSelectedRowCount();
        int row[] = Table1.getSelectedRows();
        if (Tolls.ConfigMsg("هل تريد حذف هذه العملية ؟")) {
            for (int i = 0; i < n; i++) {
                c.delete(Integer.parseInt(Table1.getValueAt(row[i], 10).toString()));

            }
            c.getAllRows(Table1);
            Tolls.MsgBox("تمت عملية الحذف بنجاح", "ثم");
        }
        BtnDelete.setEnabled(false);
        BtnUpdate.setEnabled(false);


    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void Table1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table1KeyReleased
        int row = Table1.getSelectedRow();

        frmUpdate.TxtNumberOperation2.setText(Table1.getValueAt(row, 10).toString());
        frmUpdate.TxtName2.setText(Table1.getValueAt(row, 9).toString());
        frmUpdate.TxtAdress2.setText(Table1.getValueAt(row, 8).toString());
        frmUpdate.TxtIdCard2.setText(Table1.getValueAt(row, 7).toString());
        frmUpdate.TxtProdSell2.setText(Table1.getValueAt(row, 6).toString());
        SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        try {
            frmUpdate.DCDate2.setDate(d.parse((String) Table1.getValueAt(row, 5)));
        } catch (ParseException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmUpdate.TxtPriceProdSell2.setText(Table1.getValueAt(row, 4).toString());
        frmUpdate.TxtPricePay2.setText(Table1.getValueAt(row, 3).toString());
        frmUpdate.TxtPriceStill2.setText(Table1.getValueAt(row, 2).toString());
        frmUpdate.TxtNumberParts2.setText(Table1.getValueAt(row, 1).toString());
        frmUpdate.TxtNumberPartsStill2.setText(Table1.getValueAt(row, 0).toString());
        ph.setNumberOperation(Integer.parseInt(Table1.getValueAt(row, 10).toString()));
        //System.out.println(ph.NumberOperation);
        ph.getAllRows(Table2);

        BtnDelete.setEnabled(true);
        BtnUpdate.setEnabled(true);
    }//GEN-LAST:event_Table1KeyReleased

    private void BtnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelete1ActionPerformed
        Tolls.OpenForm(frmLogin2.GetObj(), "تغيير كلمة السر ");
    }//GEN-LAST:event_BtnDelete1ActionPerformed

    private void BtnDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelete2ActionPerformed

        Tolls.OpenForm(frmSearch.getObj(), "بحث");
    }//GEN-LAST:event_BtnDelete2ActionPerformed

    private void BtnDelete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelete3ActionPerformed
        Tolls.OpenForm(new frmPrint(), "طباعة");
    }//GEN-LAST:event_BtnDelete3ActionPerformed

    private void BtnDelete5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelete5ActionPerformed
        Tolls.PrintRapoorts(Table1, "عمليات البيع");
    }//GEN-LAST:event_BtnDelete5ActionPerformed

    private void BtnDelete6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelete6ActionPerformed
        Tolls.OpenForm(frmMe.GetObj(), "المبرج");
    }//GEN-LAST:event_BtnDelete6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BtnDelete;
    public static javax.swing.JButton BtnDelete1;
    public static javax.swing.JButton BtnDelete2;
    public static javax.swing.JButton BtnDelete3;
    public static javax.swing.JButton BtnDelete5;
    public static javax.swing.JButton BtnDelete6;
    public static javax.swing.JButton BtnUpdate;
    public static javax.swing.JTable Table1;
    public static javax.swing.JTable Table2;
    public static javax.swing.JButton btnAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
